check for dependencies (#83)
* check for dependencies

* Take 2

* Take 3

* typo

* command-only version

diff --git a/FireMotD b/FireMotD
--- a/FireMotD
+++ b/FireMotD
@@ -1,12 +1,12 @@
 #!/bin/bash
 # Script name:  FireMotD
-# Version:      v8.09.171011
+# Version:      v8.10.171209
 # Created on:   10/02/2014
 # Author:       Willem D'Haese
 # Contributors: Gustavo Neves, Thomas Dietrich, Dmitry Romanenko
 # Purpose:      Bash script that will dynamically generate a message
 #               of they day for users logging in.
-# On GitHub:    https://github.com/willemdh/FireMotD
+# On GitHub:    https://github.com/OutsideIT/FireMotD
 # On OutsideIT: https://outsideit.net/FireMotD
 # Copyright:
 # This program is free software: you can redistribute it and/or modify it
@@ -159,6 +159,17 @@ VersionComparison () {
   return 3
 }
 
+function IsInstalled {
+  if [[ -x "/usr/bin/yum" ]] ; then
+    YumExec=$(which yum 2>/dev/null)
+    if $YumExec list installed "$@" >/dev/null 2>&1; then true ; else false ; fi
+  elif [[ -x "/usr/bin/zypper" ]] ; then
+    WriteLog Verbose Info "No $@ check for zypper available."
+    true
+  elif [[ -x "/usr/bin/apt-get" ]] ; then
+    if dpkg-query -l "$@" >/dev/null 2>&1 ; then true ; else false ; fi
+  fi
+}
 
 GetSessions () {
     WriteLog Verbose Info "Output who: $(who)"
@@ -1516,11 +1527,18 @@ CheckSudo () {
     return 0
 }
 
+CheckDependencies () {
+  command -v bc >/dev/null 2>&1 || { WriteLog Output Error "Unable to detect bc. Please install." >&2 ; exit 1 ; }
+  command -v jq >/dev/null 2>&1 || { WriteLog Output Error "Unable to detect jq. Please install." >&2 ; exit 1 ; }
+  command -v mpstat >/dev/null 2>&1 || { WriteLog Output Error "Unable to detect mpstat. Please install sysstat package." >&2 ; exit 1 ; }
+  command -v sponge >/dev/null 2>&1 || { WriteLog Output Error "Unable to detect sponge. Please install moreutils package." >&2 ; exit 1 ; }
+}
+
 if [[ -z $1 ]]; then
-        echo "Error! You should provide an option / parameter."
-        echo "Try:"
-        echo "    $0 --help"
-        exit 2
+  echo "Error! You should provide an option / parameter."
+  echo "Try:"
+  echo "    $0 --help"
+  exit 2
 fi
 
 while :; do
@@ -1532,7 +1550,7 @@ while :; do
         -h|--help|--Help)
             PrintHelp ; exit 0 ;;
         -s|-S|--save|--Save|--saveupdates|--SaveUpdates|--saveUpdates)
-            CheckSudo "$@" ; ExportData ; exit $? ;;
+            CheckSudo "$@" ; CheckDependencies ; ExportData ; exit $? ;;
         -HV|--hideversion|--HideVersion)
             HideVersion=1 ; shift ;;
         -sru|-SRU|--skiprepoupdate|--SkipRepoUpdate)
