Take 2

diff --git a/FireMotD b/FireMotD
--- a/FireMotD
+++ b/FireMotD
@@ -6,7 +6,7 @@
 # Contributors: Gustavo Neves, Thomas Dietrich, Dmitry Romanenko
 # Purpose:      Bash script that will dynamically generate a message
 #               of they day for users logging in.
-# On GitHub:    https://github.com/willemdh/FireMotD
+# On GitHub:    https://github.com/OutsideIT/FireMotD
 # On OutsideIT: https://outsideit.net/FireMotD
 # Copyright:
 # This program is free software: you can redistribute it and/or modify it
@@ -1533,11 +1533,11 @@ CheckSudo () {
 }
 
 CheckDependencies () {
-  if IsInstalled openssh-clients ; then WriteLog Verbose Info "Detected openssh-clients" ; else WriteLog Output Error "Unable to detect openssh-clients. Please install." ; exit 1 ; fi
-  if IsInstalled bc ; then WriteLog Verbose Info "Detected bc" ; else WriteLog Output Error "Unable to detect bc. Please install." ; exit 1 ; fi
+  command -v bc >/dev/null 2>&1 || { WriteLog Output Error "Unable to detect bc. Please install." >&2 ; exit 1 ; }
+  command -v jq >/dev/null 2>&1 || { WriteLog Output Error "Unable to detect jq. Please install." >&2 ; exit 1 ; }
   if IsInstalled sysstat ; then WriteLog Verbose Info "Detected sysstat" ; else WriteLog Output Error "Unable to detect sysstat. Please install." ; exit 1 ; fi
-  if IsInstalled jq ; then WriteLog Verbose Info "Detected jq" ; else WriteLog Output Error "Unable to detect jq. Please install." ; exit 1 ; fi
   if IsInstalled moreutils ; then WriteLog Verbose Info "Detected moreutils" ; else WriteLog Output Error "Unable to detect moreutils. Please install." ; exit 1 ; fi
+  if IsInstalled openssh-clients ; then WriteLog Verbose Info "Detected openssh-clients" ; else WriteLog Output Error "Unable to detect openssh-clients. Please install." ; exit 1 ; fi
 }
 
 if [[ -z $1 ]]; then
@@ -1563,7 +1563,6 @@ while :; do
             SkipRepoUpdate=1 ; shift ;;
         -t|-T|--Theme|--theme)
             shift ; Theme=$1
-            CheckDependencies
             LoadData
             case "$Theme" in
                 original|Original) StartOriginalBlue ; GenerateOriginal256Color ;;
